# Generated by Django 4.1.3 on 2022-12-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('auto', models.CharField(max_length=20, verbose_name='Автомобиль')),
                ('telephone', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('time_start', models.DateTimeField(auto_now=True, verbose_name='Дата начала работы')),
                ('time_end', models.DateTimeField(auto_now=True, verbose_name='Дата окончания работы')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='auto',
            field=models.CharField(max_length=20, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='telephone',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Номер телефона'),
        ),
    ]
